spring.datasource.url=jdbc:postgresql://localhost:5433/notification_db
spring.datasource.username=postgres
spring.datasource.password=Newstart@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8083

logging.level.org.hibernate.SQL=DEBUG
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

custom.message=Notification Service V1
my.name=Yogesh

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

shipment.kafka.topic=shipment-created-events

spring.kafka.consumer.properties.spring.json.trusted.packages=*
