spring.datasource.url=jdbc:postgresql://localhost:5433/notification_db
spring.datasource.username=postgres
spring.datasource.password=Newstart@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8083

logging.level.org.hibernate.SQL=DEBUG
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
 
custom.message=Notification Service V1
my.name=Yogesh

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

shipment.kafka.topic=shipment-created
spring.kafka.consumer.properties.spring.json.trusted.packages=*


spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.b2bshipping.NotificationService.event.ShipmentCreatedEvent


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sharmayogesh5star@gmail.com
spring.mail.password=slbx sikd frwc bwjw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notification.retry.scheduler-delay=60000

notification.default-type=SMS
notification.retry.base-delay=1

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=notification-service
