spring.datasource.url=jdbc:postgresql://localhost:5433/shipment_db
spring.datasource.username=postgres
spring.datasource.password= Newstart@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
custom.message=Hello V1
